services:
  registration-service:
    build:
      context: ./registration-service
    container_name: registration-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./registration-service/.env

  login-service:
    build:
      context: ./login-service
    container_name: login-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ./login-service/.env
